### ISSUE TITLE
HTTP/HTTPS Server Separation.

### ISSUE THREAD

**Issue by Hamid-Najafi** [flowcate/deephub-advanced-setup#1]
It was not a nice idea to use port 80 for Keycloak and 443 for Deephub UI.
I suggest to use Traefik for production as reverse proxy. it can also handle all SSL/TLS things as well.

**Comment by wraromer** [comment]
Thanks for your suggestion. The intention of our example is NOT to showcase how a production setup would look like but give more of an overview how the DeepHub works together with Keycloak in principle.
