### ISSUE TITLE
HTTP for open id issuer (including remote hosts not only localhost)

### ISSUE THREAD

**Issue by NilsEngelbach** [flowcate/deephub-advanced-setup#3]
I want to deploy the DeepHub and Keycloak on a test server inside our network.
For testing purposes I want to use HTTP and access the server via IP / Hostname in the network without configuring HTTPS.

It seems that the Open Id Issuer Configuration for the DeepHub UI requires HTTPS and HTTP is only available when using localhost (like in the advanced setup example).

![MicrosoftTeams-image (15)](https://github.com/flowcate/deephub-advanced-setup/assets/9214413/2f5c0132-5edd-4399-855a-149b6ea44267)

When I am using the local hostname of the server (not localhost), it gives the following error:
![image](https://github.com/flowcate/deephub-advanced-setup/assets/9214413/83bcb45f-197e-402c-bb8f-2dca265581e9)

I guess this is related to the used **angular-oauth2-oidc** library confguration:
https://manfredsteyer.github.io/angular-oauth2-oidc/docs/classes/AuthConfig.html#requireHttps
![image](https://github.com/flowcate/deephub-advanced-setup/assets/9214413/6c15c005-b0d0-4ee0-a9b5-ac2e0a822ce2)

![MicrosoftTeams-image (16)](https://github.com/flowcate/deephub-advanced-setup/assets/9214413/0786bf4c-16fc-4417-ba31-e523626a24d8)

Would it be possible to add a configuration (via envrionment variable) for the DeepHub UI, to disable HTTPS for every issuer (not only localhost) similar to the **force_https** configuration in the DeepHub?

**Comment by wraromer** [comment]
Hello Nils, thanks for your comments and suggestions. You are right, that the DeepHub UIs currently work with the default value for "requireHttps" which is therefore "remoteOnly". Upcoming versions of the DeepHub will not enforce this anymore but go with "requireHttps" set to "false". We are considering to make this configurable.

**Comment by NilsEngelbach** [comment]
Tested with version 2.5.0 - works as expected, thanks!

**Comment by wraromer** [comment]
With the release of version 2.6.0 of the DeepHub, we'll make this configurable. Version 2.6.0 will most likely be released at the end of November or beginning of December 2024.

**Note: The default will then be "remoteOnly" again.**
