### ISSUE TITLE
Enabling OAuth breaks the docker healthcheck

### ISSUE THREAD

**Issue by NilsEngelbach** [flowcate/deephub-advanced-setup#5]
When enabling Authorization (OAuth) the Docker HEALTHCHECK fails and the docker container is marked as (UNHEALTHY).

The Healthcheck calls the "/health" which seems to require Authorization:

![image](https://github.com/flowcate/deephub-advanced-setup/assets/9214413/6ab174de-a29d-4c35-8581-67bd9a2dd41d)

Version: 2.5.0

**Comment by wraromer** [comment]
Hello Nils,

thanks for the report, but for us, the health check seems to work even in a scenario with activated OAuth:

This is my output from docker ps: 

`04f6f8cc3dd3   flowcate/deephub:2.5.0                   "/app/deephub -c /da…"   11 days ago   Up About a minute (healthy)   8081/tcp, 0.0.0.0:57187->7081/tcp`

From within the container, the health check works as well:

![image](https://github.com/flowcate/deephub-advanced-setup/assets/23312565/12dd16ba-9247-48a2-97a9-0a5665afd28b)

Wolfgang

**Comment by benstadin** [comment]
It could be related to your permission settings. Do you have a wildcard rule in the permissions yaml file?

**Comment by NilsEngelbach** [comment]
I had to add the `guest` permissions (as in the advanced docker example):

```yaml
[...]
guest:
  description: A read only guest access
  '/health':
    - READ_ANY
  '/version':
    - READ_ANY
```

Now it is working, thanks!

It seems that `guest` is kind of a special key word, because i did not create a `guest` role in the identity provider.
Maybe this could be mentioned in the documentation as well?
